package com.martini.dartplayer.common

object Constants {
    const val SCAN_SONGS_NOTIFICATION_CHANNEL_ID = "SCAN_SONGS_NOTIFICATION_CHANNEL_ID"
    const val SCAN_SONGS_NOTIFICATION_ID = 1
    const val SCAN_SONGS_FINISHED_NOT_ID = 2
    const val SCAN_SONGS_GROUP_ID = "SCAN_SONGS_GROUP_ID"

    const val TABS_SONGS = 0
    const val TABS_ALBUMS = 1
    const val TABS_ARTISTS = 2
    const val TABS_PLAYLISTS = 3

    const val SCAN_MUSIC_WORKER_TAG = "SCAN_MUSIC_WORKER_TAG"

    const val ALBUM_SCREEN_ARGUMENT_NAME = "albumName"
    const val ARTIST_SCREEN_ARGUMENT_NAME = "artistName"
    const val ALBUM_FOR_ARTIST_ARTIST_ARG = "ALBUM_FOR_ARTIST_ARTIST_ARG"
    const val ALBUM_FOR_ARTIST_ALBUM_ARG = "ALBUM_FOR_ARTIST_ALBUM_ARG"
    const val PLAYLIST_SCREEN_ARG_NAME = "PLAYLIST_SCREEN_ARG_NAME"

    const val DEBOUNCE_TIME = 500L

    const val PLAYER_SERVICE_CHANNEL_ID = "Player service"
    const val PLAYER_SERVICE_NOT_ID = 100
    const val PLAYER_NOTIFICATION_GROUP_ID = "PLAYER_NOTIFICATION_GROUP_ID"

    const val MEDIA_SESSION_TAG = "DARTPLAYER_MEDIA_SESSION_TAG"

    const val DELETE_SONG_PLAYLIST_WORKER_KEY = "DELETE_SONG_PLAYLIST_WORKER_KEY"

    const val EXTRA_BUNDLE_DURATION_KEY = "EXTRA_BUNDLE_DURATION_KEY"

    const val CRASHLYTICS_DB = "CRASHLYTICS_DB"
    const val CRASHLYTICS_BOOLEAN = "CRASHLYTICS_BOOLEAN"

    const val SORT_ORDER_PREF = "SORT_ORDER_PREF"
    const val SORT_ORDER_SONG = "SORT_ORDER_SONG"
    const val SORT_ORDER_ALBUM = "SORT_ORDER_ALBUM"
    const val SORT_ORDER_ARTIST = "SORT_ORDER_ARTIST"
    const val SORT_ORDER_PLAYLIST = "SORT_ORDER_PLAYLIST"

}